apiVersion: v2
name: erpnext
description: ERPNext with SSO and some useful extras
type: application
version: "0.1.2"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
