apiVersion: v2
name: firefly
description: Firefly III with SSO and other components
type: application
version: "0.2.7"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
