apiVersion: v2
name: actualbudget
description: Actual Budget server + frontend
type: application
version: "0.1.3"
appVersion: "latest"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
