apiVersion: v2
name: gitops
description: FluxCD with some configuration
type: application
version: "0.2.0"
dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
