apiVersion: v2
name: gitops
description: FluxCD + Weave-Gitops Dashboard + extras
type: application
version: "0.1.7"
dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
