# Server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  {{ if .Values.k3s_version -}}
  version: {{ .Values.k3s_version }}
  {{- else -}}
  channel: https://update.k3s.io/v1-release/channels/stable
  {{- end }}
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  prepare:
    args:
      - prepare
      - server-plan
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  {{ if .Values.k3s_version -}}
  version: {{ .Values.k3s_version }}
  {{- else -}}
  channel: https://update.k3s.io/v1-release/channels/stable
  {{- end }}
  window:
    days:
      - monday
      - tuesday
      - wednesday
      - thursday
      - friday
    startTime: 2:00
    endTime: 5:00
    timeZone: UTC
