apiVersion: v2
name: teable
description: No-code database solution on top of Postgres
type: application
version: "0.1.3"
appVersion: "1.9.0"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
