apiVersion: v2
name: tandoor
description: Recipes + shopping lists + X
type: application
version: "0.1.11"
appVersion: "2.3"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
