apiVersion: v2
name: rocketchat
description: Rocket.Chat with SSO and some useful extras
type: application
version: "0.6.2"
appVersion: "7.11.0"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
