apiVersion: v2
name: rocketchat
description: Rocket.Chat with SSO and some useful extras
type: application
version: "0.3.2"
appVersion: "6.6.1"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
