apiVersion: v2
name: telemetry
description: Prometheus + Loki + Grafana
type: application
version: "0.5.0"
dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
