apiVersion: v2
name: nextcloud
description: Nextcloud with SSO and some useful extras
type: application
version: "0.13.1"
appVersion: "30.0.10"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
