apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pw-secret-gen
spec:
  interval: 1h
  chart:
    spec:
      chart: pw-secret-gen
      version: "^0.1.0"
      sourceRef:
        kind: HelmRepository
        name: base-config-repo
        namespace: flux-system
