apiVersion: v2
name: control
description: k8s-dashboard with proper config and extras
type: application
version: "0.1.7"
dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
