apiVersion: v2
name: control
description: Headlamp k8s control panel with plugins
type: application
version: "0.2.0"
dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
