apiVersion: v2
name: wordpress
description: Wordpress with SSO and some useful extras
type: application
version: "0.2.3"
appVersion: "6.5.0"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
