apiVersion: v2
name: storage
description: Longhorn-based storage system
type: application
version: "0.3.2"
dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
